#nullable enable
using System.Collections.Generic;
using System.Text;
using BlazingSingularity.SourceGenerators.Contracts;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BlazingSingularity.SourceGenerators.SourceGeneratorHelpers;

/// <summary>
/// Builder for generating relay command source code
/// </summary>
public class CommandSourceBuilder
{
    private readonly StringBuilder _sb = new();
    private readonly string _namespaceName;
    private readonly string _className;
    private readonly List<CommandInfo> _commands = new();

    public CommandSourceBuilder(string namespaceName, string className)
    {
        _namespaceName = namespaceName;
        _className = className;
    }

    /// <summary>
    /// Adds a command to be generated
    /// </summary>
    public void AddCommand(
        string commandType,
        string commandPropertyName,
        string commandFieldName,
        string constructorArgs
    )
    {
        _commands.Add(
            new CommandInfo(commandType, commandPropertyName, commandFieldName, constructorArgs)
        );
    }

    /// <summary>
    /// Adds a command from method analysis
    /// </summary>
    public bool TryAddCommandFromMethod(MethodDeclarationSyntax method, SemanticModel semanticModel)
    {
        var methodSymbol = semanticModel.GetDeclaredSymbol(method) as IMethodSymbol;
        if (methodSymbol == null)
            return false;

        var parameterInfo = RelayCommandHelpers.GetCommandParameters(methodSymbol);
        var canExecuteMethod = RelayCommandHelpers.FindCanExecuteMethod(
            methodSymbol,
            parameterInfo.CommandParameters
        );
        var commandTypeInfo = RelayCommandHelpers.GetCommandTypeInfo(
            methodSymbol,
            parameterInfo.CommandParameters,
            canExecuteMethod
        );

        if (commandTypeInfo == null)
            return false; // Unsupported method signature

        var commandPropertyName = RelayCommandHelpers.GetCommandPropertyName(methodSymbol.Name);
        var commandFieldName = RelayCommandHelpers.GetCommandFieldName(commandPropertyName);

        AddCommand(
            commandTypeInfo.CommandType,
            commandPropertyName,
            commandFieldName,
            commandTypeInfo.ConstructorArgs
        );
        return true;
    }

    /// <summary>
    /// Builds the final source code
    /// </summary>
    public string Build()
    {
        _sb.Clear();

        // Header
        _sb.AddAutoGeneratedHeader();
        _sb.AppendLine("using BlazingSingularity.Commands;");
        _sb.AppendLine();

        // Namespace and class
        _sb.AppendLine($"namespace {_namespaceName};");
        _sb.AppendLine();
        _sb.AppendLine($"partial class {_className}");
        _sb.AppendLine("{");

        // Generate each command
        foreach (var command in _commands)
        {
            _sb.AppendLine($"    private {command.CommandType}? {command.CommandFieldName};");
            _sb.AppendLine(
                $"    public {command.CommandType} {command.CommandPropertyName} => {command.CommandFieldName} ??= new({command.ConstructorArgs});"
            );
            _sb.AppendLine();
        }

        _sb.AppendLine("}");

        return _sb.ToString();
    }

    /// <summary>
    /// Gets the number of commands that will be generated
    /// </summary>
    public int CommandCount => _commands.Count;
}
