#nullable enable
using System.Collections.Generic;
using System.Linq;
using System.Text;
using BlazingSingularity.SourceGenerators.Contracts;

namespace BlazingSingularity.SourceGenerators.SourceGeneratorHelpers;

/// <summary>
/// Builder for generating client-side HTTP client registration (AddSingularityClients)
/// </summary>
public class ClientEndpointSourceBuilder
{
    private readonly string _assemblyName;
    private readonly List<(string Namespace, string ClassName)> _clientClasses = new();

    public ClientEndpointSourceBuilder(string assemblyName)
    {
        _assemblyName = assemblyName;
    }

    public void AddClientClass(string namespaceName, string className)
    {
        // Avoid duplicates
        if (!_clientClasses.Any(c => c.Namespace == namespaceName && c.ClassName == className))
        {
            _clientClasses.Add((namespaceName, className));
        }
    }

    public int ClientCount => _clientClasses.Count;

    /// <summary>
    /// Builds the AddSingularityClients extension method
    /// </summary>
    public string Build()
    {
        var sb = new StringBuilder();
        sb.AddAutoGeneratedHeader();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();

        // Add using statements for all namespaces
        var namespaces = _clientClasses.Select(c => c.Namespace).Distinct().OrderBy(n => n);
        foreach (var ns in namespaces)
        {
            sb.AppendLine($"using {ns};");
        }
        sb.AppendLine();

        sb.AppendLine("namespace BlazingSingularity.Endpoints;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Extension methods for registering BlazingSingularity HTTP clients");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class SingularityClientExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers all BlazingSingularity HTTP clients for dependency injection");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IServiceCollection AddSingularityClients(this IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var (namespaceName, className) in _clientClasses)
        {
            var interfaceName = EndpointHelpers.GetHttpClientInterfaceName(className);
            var clientClassName = EndpointHelpers.GetHttpClientClassName(className);

            sb.AppendLine($"        services.AddScoped<{interfaceName}, {clientClassName}>();");
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
