#nullable enable
using System.Collections.Generic;
using System.Linq;
using System.Text;
using BlazingSingularity.SourceGenerators.Contracts;

namespace BlazingSingularity.SourceGenerators.SourceGeneratorHelpers;

/// <summary>
/// Builder for generating endpoint-related source code
/// </summary>
public class EndpointSourceBuilder
{
    private readonly string _namespaceName;
    private readonly string _className;
    private readonly List<EndpointInfo> _endpoints = new();

    public EndpointSourceBuilder(string namespaceName, string className)
    {
        _namespaceName = namespaceName;
        _className = className;
    }

    public void AddEndpoint(EndpointInfo endpoint)
    {
        _endpoints.Add(endpoint);
    }

    public int EndpointCount => _endpoints.Count;

    /// <summary>
    /// Builds the in-component endpoint proxies (e.g., GetTodosEndpoint.Http())
    /// </summary>
    public string BuildComponentProxies()
    {
        var sb = new StringBuilder();
        sb.AddAutoGeneratedHeader();
        sb.AppendLine("using System.Net.Http;");
        sb.AppendLine("using System.Net.Http.Json;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.AspNetCore.Components;");
        sb.AppendLine();
        sb.AppendLine($"namespace {_namespaceName};");
        sb.AppendLine();
        sb.AppendLine($"partial class {_className}");
        sb.AppendLine("{");
        sb.AppendLine("    [Inject]");
        sb.AppendLine("    private HttpClient Http { get; set; } = default!;");
        sb.AppendLine();

        foreach (var endpoint in _endpoints)
        {
            var proxyName = EndpointHelpers.GetEndpointPropertyName(endpoint.MethodName);
            var proxyClassName = $"{endpoint.MethodName}EndpointProxy";

            // Generate proxy property
            sb.AppendLine($"    private {proxyClassName}? _{char.ToLower(proxyName[0])}{proxyName.Substring(1)};");
            sb.AppendLine($"    public {proxyClassName} {proxyName} => _{char.ToLower(proxyName[0])}{proxyName.Substring(1)} ??= new(Http);");
            sb.AppendLine();

            // Generate proxy class
            sb.AppendLine($"    public sealed class {proxyClassName}(HttpClient http)");
            sb.AppendLine("    {");
            sb.AppendLine(GenerateHttpMethod(endpoint, "        "));
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Builds the HTTP client interface and implementation
    /// </summary>
    public string BuildHttpClient()
    {
        var sb = new StringBuilder();
        sb.AddAutoGeneratedHeader();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Net.Http;");
        sb.AppendLine("using System.Net.Http.Json;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine($"namespace {_namespaceName};");
        sb.AppendLine();

        var interfaceName = EndpointHelpers.GetHttpClientInterfaceName(_className);
        var className = EndpointHelpers.GetHttpClientClassName(_className);

        // Generate interface
        sb.AppendLine($"public interface {interfaceName}");
        sb.AppendLine("{");
        foreach (var endpoint in _endpoints)
        {
            var requestParams = endpoint.RequestParameters;
            var paramList = string.Join(", ", requestParams.Select(p => $"{p.Type} {p.Name}"));
            sb.AppendLine($"    Task<{endpoint.ReturnType}> {endpoint.MethodName}({paramList});");
        }
        sb.AppendLine("}");
        sb.AppendLine();

        // Generate implementation
        sb.AppendLine($"public sealed class {className}(HttpClient http) : {interfaceName}");
        sb.AppendLine("{");
        foreach (var endpoint in _endpoints)
        {
            sb.AppendLine(GenerateHttpMethod(endpoint, "    "));
        }
        sb.AppendLine("}");

        return sb.ToString();
    }

    private string GenerateHttpMethod(EndpointInfo endpoint, string indent)
    {
        var sb = new StringBuilder();
        var requestParams = endpoint.RequestParameters;
        var paramList = string.Join(", ", requestParams.Select(p => $"{p.Type} {p.Name}"));

        sb.AppendLine($"{indent}public async Task<{endpoint.ReturnType}> Http({paramList})");
        sb.AppendLine($"{indent}{{");

        var url = BuildUrlWithParams(endpoint);
        var bodyParam = requestParams.FirstOrDefault(p => p.Source == ParameterSource.Body);

        if (endpoint.HttpMethod == "Get")
        {
            sb.AppendLine($"{indent}    var result = await http.GetFromJsonAsync<{endpoint.ReturnType}>({url});");
            sb.AppendLine($"{indent}    return result!;");
        }
        else if (endpoint.HttpMethod is "Post" or "Put" or "Patch")
        {
            var methodName = endpoint.HttpMethod switch
            {
                "Post" => "PostAsJsonAsync",
                "Put" => "PutAsJsonAsync",
                "Patch" => "PatchAsJsonAsync",
                _ => "PostAsJsonAsync"
            };

            if (bodyParam != null)
            {
                sb.AppendLine($"{indent}    var response = await http.{methodName}({url}, {bodyParam.Name});");
            }
            else
            {
                sb.AppendLine($"{indent}    var response = await http.{methodName}<object?>({url}, null);");
            }
            sb.AppendLine($"{indent}    response.EnsureSuccessStatusCode();");
            sb.AppendLine($"{indent}    var result = await response.Content.ReadFromJsonAsync<{endpoint.ReturnType}>();");
            sb.AppendLine($"{indent}    return result!;");
        }
        else if (endpoint.HttpMethod == "Delete")
        {
            sb.AppendLine($"{indent}    var response = await http.DeleteAsync({url});");
            sb.AppendLine($"{indent}    response.EnsureSuccessStatusCode();");
            sb.AppendLine($"{indent}    var result = await response.Content.ReadFromJsonAsync<{endpoint.ReturnType}>();");
            sb.AppendLine($"{indent}    return result!;");
        }

        sb.Append($"{indent}}}");
        return sb.ToString();
    }

    private string BuildUrlWithParams(EndpointInfo endpoint)
    {
        var route = endpoint.Route;
        var queryParams = endpoint.RequestParameters
            .Where(p => p.Source == ParameterSource.Query)
            .ToList();
        var routeParams = endpoint.RequestParameters
            .Where(p => p.Source == ParameterSource.Route)
            .ToList();

        // Build interpolated string
        var sb = new StringBuilder("$\"");

        // Replace route params
        var urlPart = route;
        foreach (var param in routeParams)
        {
            urlPart = urlPart.Replace($"{{{param.Name}}}", $"{{{param.Name}}}");
        }
        sb.Append(urlPart);

        // Add query params
        if (queryParams.Count > 0)
        {
            sb.Append("?");
            for (int i = 0; i < queryParams.Count; i++)
            {
                var param = queryParams[i];
                if (i > 0) sb.Append("&");

                if (param.IsNullable)
                {
                    sb.Append($"{param.Name}={{{param.Name}}}");
                }
                else
                {
                    sb.Append($"{param.Name}={{{param.Name}}}");
                }
            }
        }

        sb.Append("\"");
        return sb.ToString();
    }
}
