using System.Text;

namespace BlazingSingularity.SourceGenerators.SourceGeneratorHelpers;

public static class GenericSourceHelpers
{
    public static StringBuilder AddAutoGeneratedHeader(this StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        return sb;
    }
}
