#nullable enable
using System.Collections.Generic;
using System.Linq;
using System.Text;
using BlazingSingularity.SourceGenerators.Contracts;

namespace BlazingSingularity.SourceGenerators.SourceGeneratorHelpers;

/// <summary>
/// Builder for generating server-side endpoint registration code (MapSingularityEndpoints)
/// </summary>
public class ServerEndpointSourceBuilder
{
    private readonly string _assemblyName;
    private readonly List<(string Namespace, string ClassName, EndpointInfo Endpoint)> _endpoints = new();

    public ServerEndpointSourceBuilder(string assemblyName)
    {
        _assemblyName = assemblyName;
    }

    public void AddEndpoint(string namespaceName, string className, EndpointInfo endpoint)
    {
        _endpoints.Add((namespaceName, className, endpoint));
    }

    public int EndpointCount => _endpoints.Count;

    /// <summary>
    /// Builds the MapSingularityEndpoints extension method
    /// </summary>
    public string Build()
    {
        var sb = new StringBuilder();
        sb.AddAutoGeneratedHeader();
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace BlazingSingularity.Endpoints;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Extension methods for registering BlazingSingularity endpoints");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class SingularityEndpointExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Maps all BlazingSingularity endpoints defined in this assembly");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IEndpointRouteBuilder MapSingularityEndpoints(this IEndpointRouteBuilder endpoints)");
        sb.AppendLine("    {");

        foreach (var (namespaceName, className, endpoint) in _endpoints)
        {
            var mapMethod = EndpointHelpers.GetAspNetMethodName(endpoint.HttpMethod);
            var route = endpoint.Route;

            // Build the lambda parameters
            var serviceParams = endpoint.ServiceParameters;
            var requestParams = endpoint.RequestParameters;

            // Build parameter list for the lambda
            var lambdaParams = new List<string>();

            // Add service parameters with [FromServices] attribute
            foreach (var param in serviceParams)
            {
                lambdaParams.Add($"[Microsoft.AspNetCore.Mvc.FromServices] {param.Type} {param.Name}");
            }

            // Add request parameters with appropriate attributes
            foreach (var param in requestParams)
            {
                var attrName = param.Source switch
                {
                    ParameterSource.Query => "Microsoft.AspNetCore.Mvc.FromQuery",
                    ParameterSource.Route => "Microsoft.AspNetCore.Mvc.FromRoute",
                    ParameterSource.Body => "Microsoft.AspNetCore.Mvc.FromBody",
                    _ => "Microsoft.AspNetCore.Mvc.FromQuery"
                };
                lambdaParams.Add($"[{attrName}] {param.Type} {param.Name}");
            }

            var lambdaParamList = string.Join(", ", lambdaParams);

            // Generate the endpoint registration
            sb.AppendLine($"        // Endpoint: {className}.{endpoint.MethodName}");
            sb.AppendLine($"        endpoints.{mapMethod}(\"{route}\", async ({lambdaParamList}) =>");
            sb.AppendLine("        {");

            // Generate the method body - call the endpoint method
            // For now, we'll inline the method body
            if (!string.IsNullOrWhiteSpace(endpoint.MethodBody))
            {
                // Indent the method body
                var bodyLines = endpoint.MethodBody.Split('\n');
                foreach (var line in bodyLines)
                {
                    if (!string.IsNullOrWhiteSpace(line))
                    {
                        sb.AppendLine($"            {line.Trim()}");
                    }
                }
            }
            else
            {
                sb.AppendLine($"            throw new System.NotImplementedException(\"Endpoint {endpoint.MethodName} has no implementation.\");");
            }

            sb.AppendLine("        });");
            sb.AppendLine();
        }

        sb.AppendLine("        return endpoints;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
