#nullable enable
using System.Collections.Generic;
using System.Text;
using BlazingSingularity.SourceGenerators.Contracts;

namespace BlazingSingularity.SourceGenerators.SourceGeneratorHelpers;

/// <summary>
/// Builder for generating signal source code
/// </summary>
public class SignalSourceBuilder
{
    private readonly StringBuilder _sb = new();
    private readonly string _namespaceName;
    private readonly string _className;
    private readonly List<SignalInfo> _signals = new();

    public SignalSourceBuilder(string namespaceName, string className)
    {
        _namespaceName = namespaceName;
        _className = className;
    }

    /// <summary>
    /// Adds a signal to be generated
    /// </summary>
    public void AddSignal(
        string fieldName,
        string fieldType,
        string propertyName,
        string signalFieldName,
        string signalPropertyName
    )
    {
        _signals.Add(
            new SignalInfo(fieldName, fieldType, propertyName, signalFieldName, signalPropertyName)
        );
    }

    /// <summary>
    /// Builds the final source code
    /// </summary>
    public string Build()
    {
        _sb.Clear();

        // Header
        _sb.AddAutoGeneratedHeader();
        _sb.AppendLine("using System.Collections.Generic;");
        _sb.AppendLine("using BlazingSingularity.Signals;");
        _sb.AppendLine();

        // Namespace and class
        _sb.AppendLine($"namespace {_namespaceName};");
        _sb.AppendLine();
        _sb.AppendLine($"partial class {_className}");
        _sb.AppendLine("{");

        // Generate each signal
        foreach (var signal in _signals)
        {
            // Signal backing field
            _sb.AppendLine($"    private readonly Signal<{signal.FieldType}> {signal.SignalFieldName} = new();");
            _sb.AppendLine();

            // Property with change notification
            _sb.AppendLine($"    public {signal.FieldType} {signal.PropertyName}");
            _sb.AppendLine("    {");
            _sb.AppendLine($"        get => {signal.FieldName};");
            _sb.AppendLine("        set");
            _sb.AppendLine("        {");
            _sb.AppendLine($"            if (!EqualityComparer<{signal.FieldType}>.Default.Equals({signal.FieldName}, value))");
            _sb.AppendLine("            {");
            _sb.AppendLine($"                {signal.FieldName} = value;");
            _sb.AppendLine($"                {signal.SignalFieldName}.Notify(value);");
            _sb.AppendLine("            }");
            _sb.AppendLine("        }");
            _sb.AppendLine("    }");
            _sb.AppendLine();

            // Signal property
            _sb.AppendLine($"    public Signal<{signal.FieldType}> {signal.SignalPropertyName} => {signal.SignalFieldName};");
            _sb.AppendLine();
        }

        _sb.AppendLine("}");

        return _sb.ToString();
    }

    /// <summary>
    /// Gets the number of signals that will be generated
    /// </summary>
    public int SignalCount => _signals.Count;
}
