#nullable enable
using System.Collections.Generic;
using System.Linq;
using System.Text;
using BlazingSingularity.SourceGenerators.SourceGeneratorHelpers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace BlazingSingularity.SourceGenerators;

[Generator]
public class SignalGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var fieldDeclarations = context
            .SyntaxProvider.CreateSyntaxProvider(
                predicate: static (s, _) => IsSyntaxTargetForGeneration(s),
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx)
            )
            .Where(static f => f is not null);

        var compilationAndFields = context.CompilationProvider.Combine(
            fieldDeclarations.Collect()
        );

        context.RegisterSourceOutput(
            compilationAndFields,
            static (spc, source) => Execute(source.Left, source.Right!, spc)
        );
    }

    private static bool IsSyntaxTargetForGeneration(SyntaxNode node)
    {
        return node is FieldDeclarationSyntax f && f.AttributeLists.Count > 0;
    }

    private static FieldDeclarationSyntax? GetSemanticTargetForGeneration(
        GeneratorSyntaxContext context
    )
    {
        var fieldDeclaration = (FieldDeclarationSyntax)context.Node;

        foreach (var attributeList in fieldDeclaration.AttributeLists)
        {
            foreach (var attribute in attributeList.Attributes)
            {
                var symbolInfo = context.SemanticModel.GetSymbolInfo(attribute);
                if (symbolInfo.Symbol is IMethodSymbol attributeSymbol)
                {
                    var attributeContainingTypeSymbol = attributeSymbol.ContainingType;
                    var fullName = attributeContainingTypeSymbol.ToDisplayString();

                    if (fullName == "BlazingSingularity.Signals.SignalAttribute")
                    {
                        return fieldDeclaration;
                    }
                }
            }
        }

        return null;
    }

    private static void Execute(
        Compilation compilation,
        IEnumerable<FieldDeclarationSyntax> fields,
        SourceProductionContext context
    )
    {
        if (!fields.Any())
            return;

        // Group fields by their containing type using semantic analysis
        // This handles both regular .cs files and .razor files
        var fieldsByType = new Dictionary<INamedTypeSymbol, List<FieldDeclarationSyntax>>(
            SymbolEqualityComparer.Default
        );

        foreach (var field in fields)
        {
            var semanticModel = compilation.GetSemanticModel(field.SyntaxTree);

            // Get the containing type from the first variable's field symbol
            var firstVariable = field.Declaration.Variables.FirstOrDefault();
            if (firstVariable == null)
                continue;

            var fieldSymbol = semanticModel.GetDeclaredSymbol(firstVariable) as IFieldSymbol;
            if (fieldSymbol?.ContainingType == null)
                continue;

            var containingType = fieldSymbol.ContainingType;

            if (!fieldsByType.TryGetValue(containingType, out var fieldList))
            {
                fieldList = new List<FieldDeclarationSyntax>();
                fieldsByType[containingType] = fieldList;
            }

            fieldList.Add(field);
        }

        foreach (var kvp in fieldsByType)
        {
            var typeSymbol = kvp.Key;
            var typeFields = kvp.Value;
            var namespaceName = typeSymbol.ContainingNamespace.ToDisplayString();
            var className = typeSymbol.Name;

            // Check if the class is partial by looking at syntax declarations
            // For Razor components, they are implicitly partial (generated by Razor SDK)
            var classDeclaration = typeSymbol
                .DeclaringSyntaxReferences.Select(r => r.GetSyntax())
                .OfType<ClassDeclarationSyntax>()
                .FirstOrDefault();

            var isPartial =
                classDeclaration == null // Razor components (no ClassDeclarationSyntax in user code)
                || classDeclaration.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword));

            if (!isPartial)
            {
                var diagnostic = Diagnostic.Create(
                    DiagnosticDescriptors.BLAZING003,
                    classDeclaration!.GetLocation(),
                    className
                );
                context.ReportDiagnostic(diagnostic);
                continue;
            }

            var semanticModel = compilation.GetSemanticModel(typeFields.First().SyntaxTree);
            var source = GenerateSignalsForClass(
                namespaceName,
                className,
                typeFields,
                semanticModel
            );
            context.AddSource($"{className}.Signals.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string GenerateSignalsForClass(
        string namespaceName,
        string className,
        IEnumerable<FieldDeclarationSyntax> fields,
        SemanticModel semanticModel
    )
    {
        var builder = new SignalSourceBuilder(namespaceName, className);

        foreach (var field in fields)
        {
            foreach (var variable in field.Declaration.Variables)
            {
                var fieldSymbol = semanticModel.GetDeclaredSymbol(variable) as IFieldSymbol;
                if (fieldSymbol == null)
                    continue;

                var fieldName = fieldSymbol.Name;
                var fieldType = fieldSymbol.Type.ToDisplayString();
                var propertyName = SignalHelpers.GetPropertyName(fieldName);
                var signalPropertyName = SignalHelpers.GetSignalPropertyName(propertyName);
                var signalFieldName = SignalHelpers.GetSignalFieldName(signalPropertyName);

                builder.AddSignal(fieldName, fieldType, propertyName, signalFieldName, signalPropertyName);
            }
        }

        return builder.Build();
    }
}
